version = 1

[envs.vim-language-server]
channels = ["conda-forge", "bioconda"]
dependencies = { vim-language-server = "*" }
exposed = { vim-language-server = "vim-language-server" }

[envs.quarto]
channels = ["conda-forge", "bioconda"]
dependencies = { quarto = "*", python = "*", pandas = "*", palmerpenguins = "*", pyright = "*", r-base = "*", r-languageserver = "*", r-palmerpenguins = "*", r-rmarkdown = "*", r-tidyverse = "*" }
exposed = { python = "python", quarto = "quarto",  R = "R" }
